// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Arc4;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Arc5;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Arc6;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Spinner4;
extern lv_obj_t *ui_Spinner5;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
