// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 102);
lv_obj_set_height( ui_Panel1, 20);
lv_obj_set_x( ui_Panel1, 1 );
lv_obj_set_y( ui_Panel1, 3 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xC3130A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x031015), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 1 );
lv_obj_set_y( ui_Label2, -1 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Live Data");

ui_Spinner1 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner1, 23);
lv_obj_set_height( ui_Spinner1, 19);
lv_obj_set_x( ui_Spinner1, -64 );
lv_obj_set_y( ui_Spinner1, -148 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x820D2D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Spinner3 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner3, 23);
lv_obj_set_height( ui_Spinner3, 19);
lv_obj_set_x( ui_Spinner3, 70 );
lv_obj_set_y( ui_Spinner3, -148 );
lv_obj_set_align( ui_Spinner3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner3, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x820D2D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 53);
lv_obj_set_height( ui_Panel3, 21);
lv_obj_set_x( ui_Panel3, -55 );
lv_obj_set_y( ui_Panel3, 39 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"TIME");

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 93);
lv_obj_set_height( ui_Panel4, 21);
lv_obj_set_x( ui_Panel4, 29 );
lv_obj_set_y( ui_Panel4, 39 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"12:03AM");

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 53);
lv_obj_set_height( ui_Panel5, 21);
lv_obj_set_x( ui_Panel5, -56 );
lv_obj_set_y( ui_Panel5, 64 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"DATE");

ui_Panel6 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel6, 93);
lv_obj_set_height( ui_Panel6, 21);
lv_obj_set_x( ui_Panel6, 29 );
lv_obj_set_y( ui_Panel6, 64 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel6, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel6, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"12-03-2025");

ui_Panel9 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel9, 53);
lv_obj_set_height( ui_Panel9, 21);
lv_obj_set_x( ui_Panel9, -56 );
lv_obj_set_y( ui_Panel9, 92 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel9, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel9, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"FAN");

ui_Panel10 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel10, 93);
lv_obj_set_height( ui_Panel10, 21);
lv_obj_set_x( ui_Panel10, 29 );
lv_obj_set_y( ui_Panel10, 92 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x060B1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel10, lv_color_hex(0x170B68), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel10, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"OFF");

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 65);
lv_obj_set_height( ui_Arc1, 67);
lv_obj_set_x( ui_Arc1, -40 );
lv_obj_set_y( ui_Arc1, 25 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 0,360);
lv_arc_set_value(ui_Arc1, 60);
lv_arc_set_bg_angles(ui_Arc1,0,360);
lv_arc_set_rotation(ui_Arc1,90);

lv_obj_set_style_opa(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Arc1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"26.7'c");

ui_Arc3 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc3, 65);
lv_obj_set_height( ui_Arc3, 67);
lv_obj_set_x( ui_Arc3, 40 );
lv_obj_set_y( ui_Arc3, 25 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc3, 0,360);
lv_arc_set_value(ui_Arc3, 120);
lv_arc_set_bg_angles(ui_Arc3,0,360);

lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x9C1216), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Arc3);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"38%");

ui_Arc4 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc4, 65);
lv_obj_set_height( ui_Arc4, 67);
lv_obj_set_x( ui_Arc4, -40 );
lv_obj_set_y( ui_Arc4, 110 );
lv_obj_set_align( ui_Arc4, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc4, 0,360);
lv_arc_set_value(ui_Arc4, 120);
lv_arc_set_bg_angles(ui_Arc4,0,360);
lv_arc_set_rotation(ui_Arc4,90);

lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xEDFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_Arc4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Arc4);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"41");

ui_Arc5 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc5, 65);
lv_obj_set_height( ui_Arc5, 67);
lv_obj_set_x( ui_Arc5, 40 );
lv_obj_set_y( ui_Arc5, 110 );
lv_obj_set_align( ui_Arc5, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc5, 0,360);
lv_arc_set_value(ui_Arc5, 270);
lv_arc_set_bg_angles(ui_Arc5,0,360);
lv_arc_set_rotation(ui_Arc5,90);

lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0x078225), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_Arc5, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Arc5);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"100%");

ui_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -41 );
lv_obj_set_y( ui_Label15, 64 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Temp");

ui_Arc6 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc6, 65);
lv_obj_set_height( ui_Arc6, 67);
lv_obj_set_x( ui_Arc6, 40 );
lv_obj_set_y( ui_Arc6, 25 );
lv_obj_set_align( ui_Arc6, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc6, 0,360);
lv_arc_set_value(ui_Arc6, 120);
lv_arc_set_bg_angles(ui_Arc6,0,360);
lv_arc_set_rotation(ui_Arc6,90);

lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0x9C1216), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_opa(ui_Arc6, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 40 );
lv_obj_set_y( ui_Label17, 64 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Hum%");

ui_Label18 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -40 );
lv_obj_set_y( ui_Label18, 148 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Vibration");

ui_Label19 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 46 );
lv_obj_set_y( ui_Label19, 148 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"System");

ui_Panel7 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel7, 102);
lv_obj_set_height( ui_Panel7, 20);
lv_obj_set_x( ui_Panel7, 1 );
lv_obj_set_y( ui_Panel7, 125 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xC3130A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel7, lv_color_hex(0x031015), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Panel7, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 1 );
lv_obj_set_y( ui_Label7, -1 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Sesor Data");

ui_Spinner4 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner4, 23);
lv_obj_set_height( ui_Spinner4, 19);
lv_obj_set_x( ui_Spinner4, -64 );
lv_obj_set_y( ui_Spinner4, -25 );
lv_obj_set_align( ui_Spinner4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner4, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x820D2D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Spinner5 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner5, 23);
lv_obj_set_height( ui_Spinner5, 19);
lv_obj_set_x( ui_Spinner5, 70 );
lv_obj_set_y( ui_Spinner5, -25 );
lv_obj_set_align( ui_Spinner5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner5, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner5, lv_color_hex(0x820D2D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
